version: "2.1"

services:
  front:
    image: "homenitor/front:latest"
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 30s
    volumes:
      - ./config/frontend:/etc/nginx/conf.d
  back:
    image: "homenitor/back:latest"
    ports:
      - "3000:3000"
    depends_on:
      mqtt:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -0 /dev/null http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 30s
  mqtt:
    image: "arm32v6/eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
    healthcheck:
      test: ["CMD-SHELL", "timeout -t 5 mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
      interval: 10s
      timeout: 30s
    volumes:
      - "./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
