version: "2.1"

services:
  front:
    image: "homenitor/front:latest"
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 30s
    volumes:
      - ./config/frontend:/etc/nginx/conf.d
  back:
    image: "homenitor/back:latest"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -0 /dev/null http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 30s
