version: "2.1"

services:
  front:
    image: "homenitor/front:latest"
    restart: always
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 30s
    volumes:
      - ./config/frontend:/etc/nginx/conf.d
  back:
    image: "homenitor/back:latest"
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MQTT_HOST=mqttservice
    links:
      - "mqtt:mqttservice"
    depends_on:
      - mqtt
    healthcheck:
      test: ["CMD-SHELL", "wget -q -0 /dev/null http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 30s
  mqtt:
    image: "arm32v6/eclipse-mosquitto:latest"
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
